2021-09-05 17:20:59,598 - no description
2021-09-05 17:20:59,598 - dataset:ml-1m lr1:0.001 lr2:0.0003 kl:0.05 contrast:0.1 batch:1 model_func:fc_att
2021-09-05 17:20:59,599 - Using CUDA:0
2021-09-05 17:21:00,466 - Building net...
2021-09-05 17:21:00,481 - Net build finished.
2021-09-05 17:21:00,482 - User datasets loaded and saved.
2021-09-05 17:21:00,484 - Start training...
2021-09-05 17:21:07,489 - Traceback (most recent call last):
  File "trainMe0904.py", line 303, in <module>
    train()
  File "trainMe0904.py", line 264, in train
    vae = vae_locals.sum()
AttributeError: 'list' object has no attribute 'sum'

2021-09-05 17:21:07,489 - Error.
