2021-09-17 16:13:31,674 - no description
2021-09-17 16:13:31,674 - dataset:ml-1m lr1:0.0005 lr2:0.00015 kl:0.05 contrast:0.1 batch:1 model_func:fc_att
2021-09-17 16:13:31,674 - Using CUDA:0
2021-09-17 16:13:33,353 - Building net...
2021-09-17 16:13:33,369 - Net build finished.
2021-09-17 16:13:33,369 - User datasets loaded and saved.
2021-09-17 16:13:33,371 - Start training...
2021-09-17 16:54:32,607 - EPOCH:(0/400),STEP:1/2000000,vae:416.8808898925781,kl:4.123842239379883,contrast:9.84704875946045,prior:74.29761505126953
2021-09-17 16:54:32,609 - Start validating...
2021-09-17 16:56:26,540 - --------------------VALIDATE RESULT--------------------
2021-09-17 16:56:26,540 - HR@1:0.014315628027637197 HR@5:0.053531596944598615 HR@10:0.0900970194567757 HR@20:0.1491805130159262 HR@50:0.2677314701195198 HR@100:0.3937519786490448 
NDCG@1:0.1347364932051707 NDCG@5:0.11841350092537553 NDCG@10:0.11910667295186857 NDCG@20:0.13302512381382228 NDCG@50:0.17478161786244448 NDCG@100:0.22126940582257287 
MRR@1:0.1347364932051707 MRR@5:0.21936526350679572 MRR@10:0.23800612665793264 MRR@20:0.24830557556383642 MRR@50:0.2537102340256057 MRR@100:0.25486672772557684 
2021-09-17 16:56:26,541 - ------------------------HIGHEST RESULT----------------------
2021-09-17 16:56:26,541 - HR@1:0.014315628027637197 HR@5:0.053531596944598615 HR@10:0.0900970194567757 HR@20:0.1491805130159262 HR@50:0.2677314701195198 HR@100:0.3937519786490448 
NDCG@1:0.1347364932051707 NDCG@5:0.11841350092537553 NDCG@10:0.11910667295186857 NDCG@20:0.13302512381382228 NDCG@50:0.17478161786244448 NDCG@100:0.22126940582257287 
MRR@1:0.1347364932051707 MRR@5:0.21936526350679572 MRR@10:0.23800612665793264 MRR@20:0.24830557556383642 MRR@50:0.2537102340256057 MRR@100:0.25486672772557684 
2021-09-17 16:56:26,542 - Start client validating...
2021-09-17 16:56:26,543 - Traceback (most recent call last):
  File "trainMe0917.py", line 424, in <module>
    train()
  File "trainMe0917.py", line 383, in train
    hr, _, _ = evaluator.evaluateClient(train_dict,z_cluster,net,contrast_adversary, adversary, net_weight_cluster,contrast_adversary_weight_cluster, adversary_weight_cluster,dataloader=val_dataloader,validate=True, evaluate_users=hyper_params['evaluate_users'])
  File "/home/lili/ACVAE-PyTorch-main/Federated_train1_GMM/evaluator0917.py", line 165, in evaluateClient
    net.load_state_dict(net_weight_cluster[k])
KeyError: 5

2021-09-17 16:56:26,543 - Error.
