2021-09-05 17:03:07,299 - no description
2021-09-05 17:03:07,299 - dataset:ml-1m lr1:0.001 lr2:0.0003 kl:0.05 contrast:0.1 batch:1 model_func:fc_att
2021-09-05 17:03:07,299 - Using CUDA:0
2021-09-05 17:03:08,194 - Building net...
2021-09-05 17:03:08,210 - Net build finished.
2021-09-05 17:03:08,210 - User datasets loaded and saved.
2021-09-05 17:03:08,212 - Start training...
2021-09-05 17:03:08,212 - Traceback (most recent call last):
  File "trainMe0904.py", line 300, in <module>
    train()
  File "trainMe0904.py", line 184, in train
    print(idxs_users)
NameError: name 'idxs_users' is not defined

2021-09-05 17:03:08,213 - Error.
