2021-09-18 12:33:00,867 - no description
2021-09-18 12:33:00,868 - dataset:ml-1m lr1:0.0005 lr2:0.00015 kl:0.05 contrast:0.1 batch:1 model_func:fc_att
2021-09-18 12:33:00,868 - Using CUDA:0
2021-09-18 12:33:02,678 - Building net...
2021-09-18 12:33:02,694 - Net build finished.
2021-09-18 12:33:02,694 - User datasets loaded and saved.
2021-09-18 12:33:02,696 - Start training...
2021-09-18 13:15:10,922 - EPOCH:(0/400),STEP:1/2000000,vae:41.93846893310547,kl:0.3635586202144623,contrast:0.9707807898521423,prior:6.798472881317139
2021-09-18 13:15:10,924 - Start validating...
2021-09-18 13:17:25,761 - --------------------VALIDATE RESULT--------------------
2021-09-18 13:17:25,761 - HR@1:0.012637410266956499 HR@5:0.05359358617339918 HR@10:0.09125660493198755 HR@20:0.15004711196149612 HR@50:0.26761545585756064 HR@100:0.3924739949730992 
NDCG@1:0.12711302618495193 NDCG@5:0.11621657257583877 NDCG@10:0.11792301250221712 NDCG@20:0.13183210188996006 NDCG@50:0.1727985297170712 NDCG@100:0.2186994530377946 
MRR@1:0.12711302618495193 MRR@5:0.21448734946414874 MRR@10:0.23336878061355998 MRR@20:0.24379121337776416 MRR@50:0.24927602108031474 MRR@100:0.250432150476523 
2021-09-18 13:17:25,761 - ------------------------HIGHEST RESULT----------------------
2021-09-18 13:17:25,761 - HR@1:0.012637410266956499 HR@5:0.05359358617339918 HR@10:0.09125660493198755 HR@20:0.15004711196149612 HR@50:0.26761545585756064 HR@100:0.3924739949730992 
NDCG@1:0.12711302618495193 NDCG@5:0.11621657257583877 NDCG@10:0.11792301250221712 NDCG@20:0.13183210188996006 NDCG@50:0.1727985297170712 NDCG@100:0.2186994530377946 
MRR@1:0.12711302618495193 MRR@5:0.21448734946414874 MRR@10:0.23336878061355998 MRR@20:0.24379121337776416 MRR@50:0.24927602108031474 MRR@100:0.250432150476523 
2021-09-18 13:17:25,762 - Start client validating...
2021-09-18 13:17:25,763 - Traceback (most recent call last):
  File "trainMe0918.py", line 442, in <module>
    train()
  File "trainMe0918.py", line 397, in train
    hr, _, _ = evaluator.evaluateClient(train_dict,z_cluster,net,contrast_adversary, adversary, net_weight_cluster,contrast_adversary_weight_cluster, adversary_weight_cluster,dataloader=val_dataloader,validate=True, evaluate_users=hyper_params['evaluate_users'])
  File "/home/lili/ACVAE-PyTorch-main/Federated_train1_GMM/evaluator0918.py", line 180, in evaluateClient
    pred, _, _, _ = net(batchx)
TypeError: 'collections.OrderedDict' object is not callable

2021-09-18 13:17:25,764 - Error.
